version: 0.0
os: linux
files:
  - source: source.txt
    destination: /webapps
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 3600
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 3600
